### ISSUE TITLE
Running ./sbt run failed

### ISSUE THREAD

**Issue by flefevre** [playframework/play-java-fileupload-example#26]
it seems the right on sbt executable has not been setup
[fl218080@is227415 play-java-fileupload-example]$ chmod +x sbt
[fl218080@is227415 play-java-fileupload-example]$ chmod +x sbt-dist/bin/sbt
[fl218080@is227415 play-java-fileupload-example]$ chmod +x sbt-dist/bin/sbt-launch

**Comment by wsargent** [comment]
The sbt executable is handled by example-code-service, which packages it.  If you look at the project itself, there is no packaged sbt.

**Comment by wsargent** [comment]
Cannot replicate:

```
-rwxrw-r-- 1 wsargent wsargent   44 Jun 23 16:28 sbt
```
