### ISSUE TITLE
Access to the web failed

### ISSUE THREAD

**Issue by flefevre** [playframework/play-java-fileupload-example#27]
After running ./sbt run
And going to http://localhost:9000/
I have got one exception

SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[error] application - 

! @74flomopa - Internal server error, for (GET) [/] ->
 
play.api.UnexpectedException: Unexpected exception[RuntimeException: No application loader is configured. Please configure an application loader either using the play.application.loader configuration property, or by depending on a module that configures one. You can add the Guice support module by adding "libraryDependencies += guice" to your build.sbt.]

I have added 
libraryDependencies += guice
in build.sbt

and it seems to go one

**Comment by wsargent** [comment]
Cannot replicate.

**Comment by wsargent** [comment]
Can totally replicate.
