### ISSUE TITLE
Configuring tmp file directory

### ISSUE THREAD

**Issue by enzeart** [playframework/play-java-fileupload-example#45]
The documentation is unclear as to how one would go about configuring the directory used to store the temporary files created during file uploads.

**Comment by wsargent** [comment]
The example uses `java.nio.files.Files.createTempFile` and the Javadoc for that method is https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createTempFile(java.lang.String,%20java.lang.String,%20java.nio.file.attribute.FileAttribute...) which explains where the directory comes from -- it's part of the Files NIO API.  This is shown in the example code here oin the readme: https://github.com/playframework/play-java-fileupload-example#customizing-the-body-parser

If you want to configure another directory, you use another method that would send it somewhere else.

**Comment by enzeart** [comment]
@wsargent I wanted to avoid creating a new BodyParser as it seemed like overkill for something so simple.

Your documentation reference  pointed me in the right direction. The createTempFile method uses the default system temporary directory which can be configured with the System Property java.io.tmpdir.

So passing -Djava.io.tmpdir="directory name" to the JVM worked like a charm.
